---
#check whether config already exists
- stat: path=/etc/mysql/conf.d/galera.cnf
  register: st

#copy my.cnf file to all nodes
- name: copy maria config
  template:
      src: my.cnf.j2
      dest: /etc/mysql/my.cnf
      owner: root
      mode: 0644
  when: not st.stat.exists